"""Initial baseline

Revision ID: 81c3e3d55b90
Revises: 
Create Date: 2026-07-23 12:33:59.353674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c3e3d55b90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_is_active'), 'admins', ['is_active'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('PAPER', 'INK', 'BINDING', name='inventorycategoryenum'), nullable=False),
    sa.Column('sub_category', sa.Enum('NONE', 'SPIRAL', 'SOFT_COVER', 'HARD_COVER', 'STAPLE_PINS', name='inventorysubcategoryenum'), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_threshold', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('current_stock >= 0', name='ck_inventory_stock_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mobile', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_is_deleted'), 'students', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_students_mobile'), 'students', ['mobile'], unique=True)
    op.create_table('application_settings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_settings_setting_key'), 'application_settings', ['setting_key'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CASH', name='payment_method_enum'), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0.00', name='ck_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'PRINTING', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED', name='order_status_enum'), nullable=False),
    sa.Column('print_side', sa.Enum('SINGLE_SIDE', 'DOUBLE_SIDE', 'MULTI_PAGE', name='print_side_enum'), nullable=False),
    sa.Column('color_mode', sa.Enum('BW', 'COLOR', name='color_mode_enum'), nullable=False),
    sa.Column('binding_type', sa.Enum('NONE', 'SPIRAL', 'SOFT_COVER', 'HARD_COVER', 'STAPLE_PINS', name='binding_type_enum'), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('per_page_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('binding_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CASH', name='payment_method_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('binding_price >= 0.00', name='ck_orders_binding_price_positive'),
    sa.CheckConstraint('copies >= 1 AND copies <= 100', name='ck_orders_copies_range'),
    sa.CheckConstraint('page_count >= 1', name='ck_orders_page_count_positive'),
    sa.CheckConstraint('per_page_price >= 0.00', name='ck_orders_per_page_price_positive'),
    sa.CheckConstraint('total_price >= 0.00', name='ck_orders_total_price_positive'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_display_id'), 'orders', ['display_id'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_student_id'), 'orders', ['student_id'], unique=False)
    op.create_table('pricing_settings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('bw_single_side', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bw_double_side', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bw_multi_page', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color_single_side', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('spiral_binding_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('soft_binding_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hard_binding_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stapling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_settings_is_current'), 'pricing_settings', ['is_current'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('jwt_jti', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_admin_id'), 'sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_is_revoked'), 'sessions', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_sessions_jwt_jti'), 'sessions', ['jwt_jti'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Enum('RESTOCK', 'CONSUMPTION', 'WASTAGE', 'ADJUSTMENT', name='inventorytxntypeenum'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('stock_after_txn', sa.Integer(), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('running_cash_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_entry_type'), 'ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_order_id'), 'ledger_entries', ['order_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('target_user', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_target_user'), 'notifications', ['target_user'], unique=False)
    op.create_index(op.f('ix_notifications_target_user_id'), 'notifications', ['target_user_id'], unique=False)
    op.create_table('order_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('magic_bytes_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('TEMPORARY', 'ATTACHED', 'ORPHANED', 'DELETED', name='file_status_enum'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_files_id'), 'order_files', ['id'], unique=False)
    op.create_index(op.f('ix_order_files_order_id'), 'order_files', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_files_status'), 'order_files', ['status'], unique=False)
    op.create_index(op.f('ix_order_files_storage_path'), 'order_files', ['storage_path'], unique=False)
    op.create_index(op.f('ix_order_files_student_id'), 'order_files', ['student_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING_PAYMENT', 'PAID', 'PRINTING', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED', name='order_status_enum'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING_PAYMENT', 'PAID', 'PRINTING', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED', name='order_status_enum'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CASH', name='payment_method_enum'), nullable=False),
    sa.Column('verified_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('amount > 0.00', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_table('pickup_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='pickup_code_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_codes_code'), 'pickup_codes', ['code'], unique=False)
    op.create_index(op.f('ix_pickup_codes_id'), 'pickup_codes', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_codes_order_id'), 'pickup_codes', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickup_codes_order_id'), table_name='pickup_codes')
    op.drop_index(op.f('ix_pickup_codes_id'), table_name='pickup_codes')
    op.drop_index(op.f('ix_pickup_codes_code'), table_name='pickup_codes')
    op.drop_table('pickup_codes')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_files_student_id'), table_name='order_files')
    op.drop_index(op.f('ix_order_files_storage_path'), table_name='order_files')
    op.drop_index(op.f('ix_order_files_status'), table_name='order_files')
    op.drop_index(op.f('ix_order_files_order_id'), table_name='order_files')
    op.drop_index(op.f('ix_order_files_id'), table_name='order_files')
    op.drop_table('order_files')
    op.drop_index(op.f('ix_notifications_target_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_user'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ledger_entries_order_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_sessions_jwt_jti'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_revoked'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_admin_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_pricing_settings_is_current'), table_name='pricing_settings')
    op.drop_table('pricing_settings')
    op.drop_index(op.f('ix_orders_student_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_display_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_application_settings_setting_key'), table_name='application_settings')
    op.drop_table('application_settings')
    op.drop_index(op.f('ix_students_mobile'), table_name='students')
    op.drop_index(op.f('ix_students_is_deleted'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_is_active'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
